apiVersion: v1
kind: Service
metadata:
  name: argo-rollout-sample-service-stable
spec:
  selector:
    name: argo-rollout-sample
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: argo-rollout-sample-service-preview
spec:
  selector:
    name: argo-rollout-sample
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollout-sample-ingress
spec:
  rules:
  - host: 192.168.0.102.nip.io
    http:
      paths:
      - backend:
          service:
            name: argo-rollout-sample-service-stable
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5s
    successCondition: "result.ok && result.successPercent >= 0.90"
    failureLimit: 3
    provider:
      web:
        url: "http://192.168.0.102.nip.io/api/v1/measurement?service={{ args.service-name }}"
        jsonPath: "{$}"  
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollout-sample
spec:
  replicas: 10
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 1
        args:
        - name: service-name
          value: argo-rollout-sample-service-preview.default.svc.cluster.local
      canaryService: argo-rollout-sample-service-preview
      stableService: argo-rollout-sample-service-stable
      trafficRouting:
        nginx:
          stableIngress: argo-rollout-sample-ingress
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 40
      - pause: {duration: 1m}
      - setWeight: 60
      - pause: {duration: 1m}
      - setWeight: 80
      - pause: {duration: 1m}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: argo-rollout-sample
  template:
    metadata:
      labels:
        name: argo-rollout-sample
    spec:
      containers:
      - name: argo-rollout-sample
        image: leonardosimoura/argo-rollouts-sample:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP